import {useMemo,useRef,useState} from 'react';
import {Activity,ArrowRight,BriefcaseBusiness,CalendarClock,Camera,Check,ChevronRight,Clipboard,Download,FileText,LayoutDashboard,Menu,Plus,Search,Settings2,Target,Trash2,Upload,Users,X} from 'lucide-react';
import {backup,conversions,defaultOffers,localRules,localSuggestion,parseCsv,quoteTotal,restore,scoreProspect} from './logic';
import {statuses,type AppData,type Lead,type Offer,type Quote,type Status} from './types';
import './styles.css';
type Page='Dashboard'|'Pipeline'|'Offers'|'Prospect workbench'|'Quotes'|'Daily queue';
const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID();
const demo:Lead[]=[
 {id:'demo-1',person:'Maya Chen',business:'Gulfline Auto Club (Demo)',channel:'Instagram',url:'https://example.com/gulfline-demo',segment:'Automotive',location:'Tampa, FL',notes:'Fictional demo prospect. Hosts monthly member drives.',source:'Portfolio referral (demo)',value:575,lastContact:'2026-07-28',nextFollowUp:today(),status:'Replied',activity:[{id:'a1',at:new Date().toISOString(),text:'Demo reply recorded'}]},
 {id:'demo-2',person:'Andre Lewis',business:'North Pier Coffee (Demo)',channel:'Website',url:'https://example.com/north-pier-demo',segment:'Local business',location:'St. Petersburg, FL',notes:'Fictional demo. Website has seasonal product launches.',source:'Manual research (demo)',value:350,lastContact:'',nextFollowUp:today(),status:'Qualified',activity:[{id:'a2',at:new Date().toISOString(),text:'Added fictional demo lead'}]},
 {id:'demo-3',person:'Priya Shah',business:'Bayfront Motoring (Demo)',channel:'Email',url:'https://example.com/bayfront-demo',segment:'Automotive',location:'Tampa, FL',notes:'Fictional demo quote awaiting a decision.',source:'Event conversation (demo)',value:575,lastContact:'2026-07-25',nextFollowUp:today(),status:'Quote Sent',activity:[{id:'a3',at:new Date().toISOString(),text:'Demo quote sent'}]}
];
const initial:AppData={leads:demo,offers:defaultOffers,quotes:[],experimentStart:today()};
function load(){try{const x=localStorage.getItem('dst-revenue-os-v1');return x?restore(x):initial}catch{return initial}}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const field=(label:string,key:string,value:string|number,on:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>on(e.target.value)}/></label>;
export default function App(){const [data,setDataRaw]=useState<AppData>(load);const [page,setPage]=useState<Page>('Dashboard');const [mobile,setMobile]=useState(false);const [toast,setToast]=useState('');
 const setData=(next:AppData|((d:AppData)=>AppData))=>setDataRaw(old=>{const n=typeof next==='function'?next(old):next;localStorage.setItem('dst-revenue-os-v1',backup(n));return n});
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2500)};
 const nav:[Page,React.ReactNode][]=[['Dashboard',<LayoutDashboard/>],['Pipeline',<Users/>],['Offers',<BriefcaseBusiness/>],['Prospect workbench',<Target/>],['Quotes',<FileText/>],['Daily queue',<CalendarClock/>]];
 return <div className="shell"><aside className={mobile?'open':''}><div className="brand"><span>DST</span><div>REVENUE OS<small>LOCAL WORKSPACE · v0.1</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([n,i])=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMobile(false)}}>{i}<span>{n}</span>{page===n&&<ChevronRight/>}</button>)}</nav><div className="local"><span></span><div><b>Local only</b><small>Saved in this browser</small></div></div></aside>
 <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><small>DEVELOPER STUDIO TAMPA</small><h1>{page}</h1></div><div className="header-date"><span>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</span><button className="primary" onClick={()=>setPage('Pipeline')}><Plus/> Add lead</button></div></header>
 <div className="content">{page==='Dashboard'&&<Dashboard data={data} go={setPage}/>} {page==='Pipeline'&&<Pipeline data={data} setData={setData} notify={notify}/>} {page==='Offers'&&<Offers data={data} setData={setData}/>} {page==='Prospect workbench'&&<Workbench/>} {page==='Quotes'&&<Quotes data={data} setData={setData} notify={notify}/>} {page==='Daily queue'&&<Queue data={data} setData={setData}/>}</div></main>{toast&&<div className="toast"><Check/>{toast}</div>}</div>}

function Dashboard({data,go}:{data:AppData;go:(p:Page)=>void}){const c=conversions(data.leads), due=localRules.prioritize(data.leads).filter(l=>l.nextFollowUp&&l.nextFollowUp<=today()).slice(0,4);const count=(s:Status[])=>data.leads.filter(l=>s.includes(l.status)).length;const paid=data.leads.filter(l=>l.status==='Paid').reduce((x,l)=>x+l.value,0);const days=Math.min(30,Math.max(1,Math.ceil((Date.now()-new Date(data.experimentStart).getTime())/86400000)+1));const active=data.offers.find(o=>o.active);
return <><section className="hero"><div><p className="eyebrow">TODAY'S FOCUS</p><h2>{due.length?`${due.length} relationship${due.length>1?'s':''} need a thoughtful next step.`:'Your queue is clear. Add one well-matched prospect.'}</h2><p>Build demand through relevant work, clear scope, and professional follow-through.</p></div><button onClick={()=>go('Daily queue')}>Open 20-minute queue <ArrowRight/></button></section>
<div className="stats">{[['New',count(['New','Researching','Ready to Contact'])],['Contacted',count(['Contacted'])],['Replies',count(['Replied','Qualified'])],['Quotes',count(['Quote Sent'])],['Bookings',count(['Booked','Delivered','Paid'])],['Paid revenue',money(paid)]].map(([a,b])=><article><small>{a}</small><strong>{b}</strong></article>)}</div>
<div className="grid two"><section className="panel"><div className="panel-head"><div><p className="eyebrow">ACTION REQUIRED</p><h3>Due today</h3></div><button className="text" onClick={()=>go('Daily queue')}>View queue</button></div>{due.length?due.map(l=><div className="lead-row"><div className="avatar">{l.business[0]}</div><div><b>{l.business}</b><small>{l.person} · {l.channel}</small></div><span className="pill">{l.status}</span></div>):<Empty icon={<Check/>} title="Nothing overdue" text="Research one promising local business or review your active offer."/>}</section>
<section className="panel"><p className="eyebrow">FUNNEL HEALTH</p><h3>Conversion rates</h3>{[['Response',c.response],['Quote',c.quote],['Booking',c.booking]].map(([n,v])=><div className="rate"><span>{n as string}</span><div><i style={{width:`${(v as number)*100}%`}}/></div><b>{Math.round((v as number)*100)}%</b></div>)}<p className="hint">Rates use reached → replied → quoted → booked stages. Small samples are directional.</p></section></div>
<section className="panel experiment"><div><p className="eyebrow">30-DAY OFFER VALIDATION</p><h3>{active?.name||'Choose an active offer'}</h3><p>Day {days} of 30 · Test whether one specific offer earns qualified replies and bookings.</p></div><div className="ring" style={{'--p':`${days/30*360}deg`} as React.CSSProperties}><span>{days}<small>/ 30</small></span></div><div className="experiment-metrics"><b>{count(['Contacted','Replied','Qualified','Quote Sent','Booked','Delivered','Paid'])}<small>conversations</small></b><b>{count(['Replied','Qualified','Quote Sent','Booked','Delivered','Paid'])}<small>replies</small></b><b>{count(['Booked','Delivered','Paid'])}<small>bookings</small></b></div></section></>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty">{icon}<b>{title}</b><p>{text}</p></div>}

function Pipeline({data,setData,notify}:{data:AppData;setData:(f:(d:AppData)=>AppData)=>void;notify:(s:string)=>void}){const [q,setQ]=useState(''),[filter,setFilter]=useState('All'),[edit,setEdit]=useState<Lead|null>(null);const file=useRef<HTMLInputElement>(null),csv=useRef<HTMLInputElement>(null);const shown=data.leads.filter(l=>(filter==='All'||l.status===filter)&&`${l.person} ${l.business} ${l.notes}`.toLowerCase().includes(q.toLowerCase()));const blank=():Lead=>({id:uid(),person:'',business:'',channel:'Instagram',url:'',segment:'Automotive',location:'Tampa, FL',notes:'',source:'Manual research',value:350,lastContact:'',nextFollowUp:'',status:'New',activity:[]});
 const save=(l:Lead)=>{if(!l.person.trim()&&!l.business.trim()){notify('Add a person or business name.');return}setData(d=>({...d,leads:d.leads.some(x=>x.id===l.id)?d.leads.map(x=>x.id===l.id?{...l,activity:[...l.activity,{id:uid(),at:new Date().toISOString(),text:'Lead details updated'}]}:x):[...d.leads,{...l,activity:[{id:uid(),at:new Date().toISOString(),text:'Lead created'}]}]}));setEdit(null);notify('Lead saved locally')};
 const exportCsv=()=>download('dst-leads.csv',['person,business,channel,url,segment,location,notes,source,value,lastContact,nextFollowUp,status',...data.leads.map(l=>[l.person,l.business,l.channel,l.url,l.segment,l.location,l.notes,l.source,l.value,l.lastContact,l.nextFollowUp,l.status].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n'));
 const backupAll=()=>download('dst-revenue-os-backup.json',backup(data));
 const restoreFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const f=e.target.files?.[0];if(!f)return;const restored=restore(await f.text());setData(()=>restored);notify('Backup restored')}catch(err){notify(err instanceof Error?err.message:'Restore failed')}};
 const importCsv=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const f=e.target.files?.[0];if(!f)return;const leads=parseCsv(await f.text());setData(d=>({...d,leads:[...d.leads,...leads]}));notify(`${leads.length} leads imported`)}catch(err){notify(err instanceof Error?err.message:'CSV import failed')}finally{e.target.value=''}};
 return <><div className="toolbar"><div className="search"><Search/><input aria-label="Search leads" placeholder="Search person, business, or notes…" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{statuses.map(s=><option>{s}</option>)}</select><button onClick={exportCsv}><Download/> CSV</button><button onClick={()=>csv.current?.click()}><Upload/> Import CSV</button><input ref={csv} hidden type="file" accept=".csv,text/csv" onChange={importCsv}/><button onClick={backupAll}><Download/> Backup</button><button onClick={()=>file.current?.click()}><Upload/> Restore</button><input ref={file} hidden type="file" accept="application/json" onChange={restoreFile}/><button className="primary" onClick={()=>setEdit(blank())}><Plus/> New lead</button></div>
<section className="panel table-wrap"><table><thead><tr><th>Prospect</th><th>Status</th><th>Segment</th><th>Next follow-up</th><th>Value</th><th></th></tr></thead><tbody>{shown.map(l=><tr key={l.id}><td><b>{l.business||l.person}</b><small>{l.person}{l.channel&&` · ${l.channel}`}</small></td><td><span className="pill">{l.status}</span></td><td>{l.segment}</td><td className={l.nextFollowUp&&l.nextFollowUp<=today()?'due':''}>{l.nextFollowUp||'Not set'}</td><td>{money(l.value)}</td><td><button className="icon" aria-label={`Edit ${l.business}`} onClick={()=>setEdit(l)}><Settings2/></button></td></tr>)}</tbody></table>{!shown.length&&<Empty icon={<Users/>} title="No matching leads" text="Clear the filters or add a specific prospect worth learning about."/>}</section>
{edit&&<LeadModal lead={edit} set={setEdit} save={save} remove={()=>{if(confirm('Delete this lead and its activity history?')){setData(d=>({...d,leads:d.leads.filter(x=>x.id!==edit.id)}));setEdit(null);notify('Lead deleted')}}}/>}</>}
function LeadModal({lead,set,save,remove}:{lead:Lead;set:(l:Lead|null)=>void;save:(l:Lead)=>void;remove:()=>void}){const u=(k:keyof Lead,v:unknown)=>set({...lead,[k]:v});return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&set(null)}><div className="modal" role="dialog" aria-modal><div className="panel-head"><div><p className="eyebrow">LEAD RECORD</p><h3>{lead.business||'New prospect'}</h3></div><button className="icon" onClick={()=>set(null)}><X/></button></div><div className="form-grid">{field('Person','person',lead.person,v=>u('person',v))}{field('Business','business',lead.business,v=>u('business',v))}<label>Channel<select value={lead.channel} onChange={e=>u('channel',e.target.value)}>{['Instagram','Email','Website','Text','Referral','In person'].map(x=><option>{x}</option>)}</select></label>{field('Profile / website URL','url',lead.url,v=>u('url',v),'url')}{field('Market segment','segment',lead.segment,v=>u('segment',v))}{field('Location','location',lead.location,v=>u('location',v))}{field('Source','source',lead.source,v=>u('source',v))}{field('Estimated value','value',lead.value,v=>u('value',Number(v)),'number')}<label>Status<select value={lead.status} onChange={e=>u('status',e.target.value as Status)}>{statuses.map(x=><option>{x}</option>)}</select></label>{field('Last contact','lastContact',lead.lastContact,v=>u('lastContact',v),'date')}{field('Next follow-up','nextFollowUp',lead.nextFollowUp,v=>u('nextFollowUp',v),'date')}<label className="wide">Notes<textarea value={lead.notes} onChange={e=>u('notes',e.target.value)} rows={3}/></label></div>{lead.activity.length>0&&<details><summary>Activity history ({lead.activity.length})</summary>{[...lead.activity].reverse().map(a=><p className="history"><Activity/>{new Date(a.at).toLocaleString()} — {a.text}</p>)}</details>}<div className="modal-actions"><button className="danger" onClick={remove}><Trash2/> Delete</button><span/><button onClick={()=>set(null)}>Cancel</button><button className="primary" onClick={()=>save(lead)}>Save lead</button></div></div></div>}

function Offers({data,setData}:{data:AppData;setData:(f:(d:AppData)=>AppData)=>void}){const [selected,setSelected]=useState(data.offers[0]?.id);const offer=data.offers.find(o=>o.id===selected);const update=(k:keyof Offer,v:unknown)=>setData(d=>({...d,offers:d.offers.map(o=>o.id===selected?{...o,[k]:v}:o)}));return <div className="offer-layout"><div><p className="eyebrow">YOUR SERVICES</p>{data.offers.map(o=><button className={`offer-card ${selected===o.id?'selected':''}`} onClick={()=>setSelected(o.id)}><Camera/><div><b>{o.name}</b><small>{money(o.price)} · {o.duration}</small></div>{o.active&&<span className="active-tag">ACTIVE TEST</span>}</button>)}</div>{offer&&<section className="panel editor"><div className="panel-head"><div><p className="eyebrow">OFFER DETAILS</p><h3>{offer.name}</h3></div><button onClick={()=>setData(d=>({...d,offers:d.offers.map(o=>({...o,active:o.id===offer.id}))}))}>{offer.active?'Active experiment':'Make active experiment'}</button></div><div className="form-grid">{field('Offer name','name',offer.name,v=>update('name',v))}{field('Price','price',offer.price,v=>update('price',Number(v)),'number')}{field('Deposit (%)','deposit',offer.deposit,v=>update('deposit',Number(v)),'number')}{field('Shoot duration','duration',offer.duration,v=>update('duration',v))}<label className="wide">Deliverables<textarea value={offer.deliverables} onChange={e=>update('deliverables',e.target.value)}/></label>{field('Turnaround','turnaround',offer.turnaround,v=>update('turnaround',v))}{field('Included revisions','revisions',offer.revisions,v=>update('revisions',Number(v)),'number')}{field('Travel radius','radius',offer.radius,v=>update('radius',v))}<label className="wide">Usage rights<textarea value={offer.usage} onChange={e=>update('usage',e.target.value)}/></label><label className="wide">Optional add-ons<textarea value={offer.addons} onChange={e=>update('addons',e.target.value)}/></label></div><p className="hint">Prices are editable starting points, not claims about market value or prior work.</p></section>}</div>}

function Workbench(){const [facts,setFacts]=useState(''),[segment,setSegment]=useState('automotive businesses'),[draft,setDraft]=useState(''),[rules,setRules]=useState([{term:'Tampa',points:2},{term:'event',points:2},{term:'launch',points:2},{term:'outdated photos',points:3}]);const score=scoreProspect(facts,rules);return <div className="grid workbench"><section className="panel"><p className="eyebrow">PASTE ONLY VERIFIED FACTS</p><h3>Prospect context</h3><label>Segment<input value={segment} onChange={e=>setSegment(e.target.value)}/></label><label>Facts from a public profile or conversation<textarea rows={10} value={facts} onChange={e=>setFacts(e.target.value)} placeholder="Example: Tampa dealership. Their website announces an August cars-and-coffee event. Recent posts use phone photos."/></label><p className="hint">Nothing is fetched or scraped. Avoid sensitive personal data.</p></section><section className="panel"><p className="eyebrow">TRANSPARENT LOCAL SCORING</p><h3>Fit score: {score} points</h3>{rules.map((r,i)=><div className="rule"><input value={r.term} aria-label="Rule term" onChange={e=>setRules(x=>x.map((a,j)=>j===i?{...a,term:e.target.value}:a))}/><input type="number" value={r.points} aria-label="Rule points" onChange={e=>setRules(x=>x.map((a,j)=>j===i?{...a,points:Number(e.target.value)}:a))}/><span>{facts.toLowerCase().includes(r.term.toLowerCase())?'Matched':'—'}</span></div>)}<div className="recommend"><Target/><div><b>{score>=5?'Review for outreach':score>=2?'Research one more detail':'Do not contact yet'}</b><p>{score>=5?'Several editable fit signals match. Confirm the facts before using them.':'More relevant context will make the decision and message less generic.'}</p></div></div><button className="primary full" onClick={()=>setDraft(localSuggestion.suggest(facts,segment))}>Create rules-based draft</button></section>{draft&&<section className="panel draft"><p className="eyebrow">REVIEW REQUIRED · NEVER AUTO-SENT</p><h3>Outreach draft</h3><textarea rows={6} value={draft} onChange={e=>setDraft(e.target.value)}/><button onClick={()=>navigator.clipboard.writeText(draft)}><Clipboard/> Copy after review</button><p className="hint">Verify every detail, edit into your voice, then choose whether to send it manually.</p></section>}</div>}

function Quotes({data,setData,notify}:{data:AppData;setData:(f:(d:AppData)=>AppData)=>void;notify:(s:string)=>void}){const [leadId,setLead]=useState(data.leads[0]?.id||''),[offerId,setOffer]=useState(data.offers[0]?.id||''),[editing,setEditing]=useState<Quote|null>(null);const lead=data.leads.find(l=>l.id===leadId),offer=data.offers.find(o=>o.id===offerId);const create=()=>{if(!lead||!offer)return;const revs=data.quotes.filter(q=>q.leadId===lead.id).length;setEditing({id:uid(),number:`DST-${new Date().getFullYear()}-${String(data.quotes.length+1).padStart(3,'0')}`,leadId:lead.id,offerId:offer.id,revision:revs+1,scope:offer.name,schedule:'Schedule by mutual agreement',deliverables:offer.deliverables,price:offer.price,deposit:offer.deposit,turnaround:offer.turnaround,usage:offer.usage,expiration:new Date(Date.now()+14*86400000).toISOString().slice(0,10),terms:'Deposit reserves the date. Remaining balance is due before final delivery. Changes outside this scope require written approval.',created:today()})};
 const save=()=>{if(!editing)return;setData(d=>({...d,quotes:[...d.quotes.filter(q=>q.id!==editing.id),editing],leads:d.leads.map(l=>l.id===editing.leadId?{...l,status:'Quote Sent',activity:[...l.activity,{id:uid(),at:new Date().toISOString(),text:`Quote ${editing.number} revision ${editing.revision} saved`}]}:l)}));notify('Quote saved; lead moved to Quote Sent');setEditing(null)};
 return <>{!editing?<><section className="panel quote-start"><p className="eyebrow">BUILD A QUOTE</p><h2>Clear scope makes decisions easier.</h2><p>Create a professional proposal without implying signatures or payment processing.</p><div className="form-grid"><label>Lead<select value={leadId} onChange={e=>setLead(e.target.value)}>{data.leads.map(l=><option value={l.id}>{l.business||l.person}</option>)}</select></label><label>Offer<select value={offerId} onChange={e=>setOffer(e.target.value)}>{data.offers.map(o=><option value={o.id}>{o.name} — {money(o.price)}</option>)}</select></label></div><button className="primary" disabled={!lead||!offer} onClick={create}>Start quote <ArrowRight/></button></section><section className="panel"><div className="panel-head"><h3>Saved quotes</h3><span>{data.quotes.length} total</span></div>{data.quotes.length?data.quotes.map(q=><div className="quote-row"><div><b>{q.number} · Rev {q.revision}</b><small>{data.leads.find(l=>l.id===q.leadId)?.business} · {q.created}</small></div><strong>{money(q.price)}</strong><button onClick={()=>setEditing({...q,id:uid(),revision:q.revision+1,created:today()})}>New revision</button></div>):<Empty icon={<FileText/>} title="No saved quotes" text="Select a lead and offer above to create the first clear scope."/>}</section></>:<QuoteEditor quote={editing} set={setEditing} save={save} lead={data.leads.find(l=>l.id===editing.leadId)}/>}</>}
function QuoteEditor({quote,set,save,lead}:{quote:Quote;set:(q:Quote|null)=>void;save:()=>void;lead?:Lead}){const u=(k:keyof Quote,v:unknown)=>set({...quote,[k]:v});return <section className="quote-doc panel"><div className="no-print panel-head"><button onClick={()=>set(null)}>← Cancel</button><div><button onClick={()=>window.print()}>Print / Save PDF</button><button className="primary" onClick={save}>Save revision</button></div></div><div className="quote-brand"><div className="brand-mark">DST</div><div>DEVELOPER STUDIO TAMPA<small>PHOTOGRAPHY · TAMPA, FL</small></div><div><b>QUOTE</b><span>{quote.number} · REV {quote.revision}</span></div></div><div className="quote-for"><div><small>PREPARED FOR</small><h2>{lead?.business||lead?.person}</h2><p>{lead?.person}<br/>{lead?.location}</p></div><div><small>ISSUED</small><p>{quote.created}</p><small>VALID THROUGH</small><input type="date" value={quote.expiration} onChange={e=>u('expiration',e.target.value)}/></div></div><div className="quote-fields">{field('Scope','scope',quote.scope,v=>u('scope',v))}{field('Schedule','schedule',quote.schedule,v=>u('schedule',v))}<label>Deliverables<textarea value={quote.deliverables} onChange={e=>u('deliverables',e.target.value)}/></label>{field('Turnaround','turnaround',quote.turnaround,v=>u('turnaround',v))}<label>Usage rights<textarea value={quote.usage} onChange={e=>u('usage',e.target.value)}/></label>{field('Project price','price',quote.price,v=>u('price',Number(v)),'number')}{field('Deposit (%)','deposit',quote.deposit,v=>u('deposit',Number(v)),'number')}<label>Terms<textarea value={quote.terms} onChange={e=>u('terms',e.target.value)}/></label></div><div className="totals"><span>Deposit to reserve date <b>{money(quoteTotal(quote.price)*quote.deposit/100)}</b></span><strong>PROJECT TOTAL <b>{money(quoteTotal(quote.price))}</b></strong></div><p className="quote-note">This quote is a scope proposal only. Acceptance, invoicing, and payment are handled separately.</p></section>}

function Queue({data,setData}:{data:AppData;setData:(f:(d:AppData)=>AppData)=>void}){const queue=localRules.prioritize(data.leads).slice(0,6);const [done,setDone]=useState<string[]>([]);return <><section className="hero queue-hero"><div><p className="eyebrow">A CALM, FOCUSED ROUTINE</p><h2>20 minutes. One useful step at a time.</h2><p>5 min review · 10 min respond or follow up · 5 min improve the next prospect.</p></div><div className="timer">20:00<small>Suggested focus</small></div></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">PRIORITIZED LOCALLY</p><h3>Today's queue</h3></div><span>{done.length}/{queue.length} reviewed</span></div>{queue.length?queue.map((l,i)=>{const n=localRules.next(l);return <div className={`queue-item ${done.includes(l.id)?'complete':''}`}><button className="check" onClick={()=>setDone(x=>x.includes(l.id)?x.filter(a=>a!==l.id):[...x,l.id])}>{done.includes(l.id)&&<Check/>}</button><span className="order">0{i+1}</span><div><b>{n.action}</b><h4>{l.business||l.person}</h4><p>{n.why}</p></div><span className="pill">{l.status}</span><select aria-label={`Update status for ${l.business}`} value={l.status} onChange={e=>setData(d=>({...d,leads:d.leads.map(x=>x.id===l.id?{...x,status:e.target.value as Status}:x)}))}>{statuses.map(s=><option>{s}</option>)}</select></div>}):<Empty icon={<Check/>} title="Queue complete" text="No urgent work is hiding here. Use the time to refine the active offer."/>}</section></>}
function download(name:string,text:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
