import {statuses,type AppData,type Lead,type Offer,type Status} from './types';
export interface PrioritizationProvider {prioritize(leads:Lead[],today?:string):Lead[]}
export interface SuggestionProvider {suggest(facts:string,segment:string):string}
export interface NextActionProvider {next(lead:Lead,today?:string):{action:string;why:string}}
const rank:Record<Status,number>={'Replied':100,'Quote Sent':85,'Qualified':70,'Ready to Contact':60,'New':45,'Contacted':40,'Researching':30,'Booked':10,'Delivered':8,'Paid':0,'Lost':0};
export const localRules:PrioritizationProvider&NextActionProvider={
 prioritize:(leads,today=new Date().toISOString().slice(0,10))=>[...leads].filter(l=>!['Paid','Lost'].includes(l.status)).sort((a,b)=>(rank[b.status]+(b.nextFollowUp&&b.nextFollowUp<=today?50:0))-(rank[a.status]+(a.nextFollowUp&&a.nextFollowUp<=today?50:0))),
 next:(l,today=new Date().toISOString().slice(0,10))=>l.nextFollowUp&&l.nextFollowUp<=today?{action:'Follow up today',why:'The planned follow-up date is due.'}:l.status==='Replied'?{action:'Respond thoughtfully',why:'They replied and are waiting for a clear next step.'}:l.status==='Quote Sent'?{action:'Check in on the quote',why:'A decision is pending; offer to clarify scope.'}:l.status==='Qualified'?{action:'Prepare a personal note',why:'The prospect matches the offer and has not been contacted.'}:{action:'Research one useful detail',why:'Better context enables relevant, non-generic outreach.'}
};
export const localSuggestion:SuggestionProvider={suggest:(facts,segment)=>facts.trim()?`Hi — I noticed ${facts.trim().replace(/[.!]+$/, '')}. I photograph ${segment||'Tampa businesses'} with a focus on clear, polished assets. If fresh visuals would be useful, I can send a concise scope and examples. No pressure either way.`:'Add a specific, verifiable fact before drafting outreach.'};
export function conversions(leads:Lead[]){const contacted=leads.filter(l=>!['New','Researching','Ready to Contact'].includes(l.status)).length;const replies=leads.filter(l=>['Replied','Qualified','Quote Sent','Booked','Delivered','Paid'].includes(l.status)).length;const quotes=leads.filter(l=>['Quote Sent','Booked','Delivered','Paid'].includes(l.status)).length;const bookings=leads.filter(l=>['Booked','Delivered','Paid'].includes(l.status)).length;return {response:contacted?replies/contacted:0,quote:replies?quotes/replies:0,booking:quotes?bookings/quotes:0}}
export const quoteTotal=(price:number,addons:number=0)=>Math.max(0,price)+Math.max(0,addons);
export function backup(data:AppData){return JSON.stringify({schema:1,exportedAt:new Date().toISOString(),data},null,2)}
export function restore(raw:string):AppData{const parsed=JSON.parse(raw);if(parsed?.schema!==1||!Array.isArray(parsed?.data?.leads)||!Array.isArray(parsed?.data?.offers)||!Array.isArray(parsed?.data?.quotes))throw new Error('This is not a valid DST Revenue OS backup.');return parsed.data}
export function scoreProspect(facts:string,rules:{term:string;points:number}[]){const lower=facts.toLowerCase();return rules.reduce((sum,r)=>sum+(lower.includes(r.term.toLowerCase())?r.points:0),0)}
export function parseCsv(raw:string):Lead[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<raw.length;i++){const ch=raw[i];if(ch==='"'&&quoted&&raw[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&raw[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(x=>x.trim())||[];const required=['person','business','channel','url','segment','location','notes','source','value','lastContact','nextFollowUp','status'];if(!required.every(h=>headers.includes(h)))throw new Error('CSV headers do not match the DST lead export format.');return rows.map(values=>{const x=Object.fromEntries(headers.map((h,i)=>[h,values[i]||'']));return{id:crypto.randomUUID(),person:x.person,business:x.business,channel:x.channel,url:x.url,segment:x.segment,location:x.location,notes:x.notes,source:x.source,value:Number(x.value)||0,lastContact:x.lastContact,nextFollowUp:x.nextFollowUp,status:statuses.includes(x.status as Status)?x.status as Status:'New',activity:[{id:crypto.randomUUID(),at:new Date().toISOString(),text:'Imported from CSV'}]}})}
export const defaultOffers:Offer[]=[
 {id:'auto',name:'Automotive Photo Session',price:450,deposit:30,duration:'45–60 minutes',deliverables:'15+ edited high-resolution images',turnaround:'5 business days',revisions:1,radius:'20 miles from Tampa',usage:'Organic web and social use',addons:'Additional images; extended travel',active:true},
 {id:'reel',name:'Premium Automotive Session',price:850,deposit:30,duration:'2 hours',deliverables:'40+ edited images with an optional short vertical reel',turnaround:'7 business days',revisions:1,radius:'20 miles from Tampa',usage:'Organic web and social use',addons:'Additional reel; expedited delivery',active:false},
 {id:'event',name:'Commercial Coverage',price:1500,deposit:30,duration:'Custom scope',deliverables:'Bespoke commercial photo and video deliverables',turnaround:'By project scope',revisions:1,radius:'Quoted per project',usage:'Defined in the commercial quote',addons:'Event coverage; additional production; expedited delivery',active:false}
];
